### ISSUE TITLE
Index issue arises for certain genome + max_mol_len combination

### ISSUE THREAD

**Issue by Zhaoyang-Jia** [biointec/omsim#13]
![Screenshot from 2023-09-18 11-17-17](https://github.com/biointec/omsim/assets/64402348/6ad2fc04-1714-42f4-8a25-c6d03005787a)
There seem to be an issue with indexing during cut_long_molecule. In noise.py: line 225, `l = random.randint(int(m[idx - 1][0]) + 1, self.settings.max_mol_len) + (l % 1)`, under certain combination of genome (nicks positioning and length) + max_mol_len parameter, `int(m[idx - 1][0])` equals to `self.settings.max_mol_len`. And adding 1 to it result in the lowerbound becoming bigger than the upperbound in the random.randint() function, throwing the error.

So far, I have found two methods both can independently resolve this issue.
1) artificially adding 1 to all `self.settings.max_mol_len`, this includes the line mentioned above and all lines that check inequality with `self.settings.max_mol_len` (replace with `self.settings.max_mol_len + 1`). The effect of this seem to be very minor. For example, instead of allowing max 600,000 molecules, we sometime may see up to 600,001 bp molecules.
2) remove the +1 in `int(m[idx - 1][0]) + 1` on the line mentioned above. But I do not know if this will result in cutting the molecule right on the nick, creating a wrong output.

fasta.gz: https://easyupload.io/layk1t
templates: https://easyupload.io/m/n269mn

**Comment by gmiclotte** [comment]
Hello, thanks for reporting this issue!

This should now be fixed in release [1.1.8](https://github.com/biointec/omsim/releases/tag/v1.1.8), please let me know if this issue persists.

Kind regards
Giles Miclotte

**Comment by Zhaoyang-Jia** [comment]
I have tried v1.1.8. The above mentioned issue is fixed but a new problem occurred. I submitted a new issue post.
Thank you for your time!

**Comment by gmiclotte** [comment]
Thanks for the feedback !
