### ISSUE TITLE
ValueError: too many values to unpack (expected 2) on calling cut_long_molecule(l,m)

### ISSUE THREAD

**Issue by Zhaoyang-Jia** [biointec/omsim#14]
![Screenshot from 2023-09-20 11-57-16](https://github.com/biointec/omsim/assets/64402348/f4fbb2a6-30f0-4011-b577-74964eaa898c)
I have also met this problem in the solution 1 I mentioned in the previous post. However, solution 2 seems to not produce this error.
This time, I was unable to separate the FASTA seqences and reproduce the problem on a smaller dataset, so I uploaded the entire FASTA that produced the problem. The templates are the same as before.
https://easyupload.io/hwstus

**Comment by gmiclotte** [comment]
Hello, thanks again for reporting this issue!

This should now be fixed in release [1.1.9](https://github.com/biointec/omsim/releases/tag/v1.1.9), please let me know if this issue persists.

Kind regards
Giles Miclotte

**Comment by Zhaoyang-Jia** [comment]
It worked out great, thank you!

**Comment by gmiclotte** [comment]
That's great, thank you for the feedback!
